### ISSUE TITLE
Namen zum Github Nickname

### ISSUE THREAD

**Issue by Lacritz** [ProPra16/programmierpraktikum-abschlussprojekt-goldener-ring#4]
Moin,

gebt mir bitte mal zu den Nicknamen die passenden Namen von euch!

Gruß,
Timo

**Comment by DiggeHummel** [comment]
Lars <-> DiggeHummel

**Comment by ghost** [comment]
Kirill Borodkin => bugiman13

**Comment by erdelf** [comment]
Simon Latusek

**Comment by baris8** [comment]
Baris -> baris8

Am 12. Juli 2016 um 09:00 schrieb Timo Grün notifications@github.com:
