### ISSUE TITLE
NullPointer Exception

### ISSUE THREAD

**Issue by Lacritz** [ProPra16/programmierpraktikum-abschlussprojekt-goldener-ring#6]
Hi, 
ich bekomme sowohl über "./gradlew clean build" als auch über das Kompilieren der Main Methode eine Exception. Bitte fixen!

"java.io.FileNotFoundException: Katalog.xml (No such file or directory)"

Gruß,
Timo

**Comment by DiggeHummel** [comment]
![gradle beweis](https://cloud.githubusercontent.com/assets/19999089/16900137/053a0a0c-4c1c-11e6-9ddb-479edb32f461.PNG)
Wie sie sehen habe ich das Projekt erst geklont und dann "./gradlew clean build" aufgerufen. Somit habe ich eigentlich genau die Schritte befolgt die sie befolgt haben müssen. Sicher das sie keinen Fehler gemacht haben?

**Comment by erdelf** [comment]
Obwohl diese Probleme nicht beim Compilen auftreten können sondern erst in der runtime... entsteht dieses Problem natürlich dann, wenn der Katalog nicht im root Verzeichnis des ausgeführten Codes liegt, wie von der Aufgabenstellung vorgeschrieben. Wenn sie möchten, ist es (wahrscheinlich) möglich, gradle das erledigen zu lassen.

**Comment by erdelf** [comment]
also, update für gradle ist oben. Schreiben Sie gerne sollten sie noch weitere Probleme haben.

**Comment by Lacritz** [comment]
Vielen Dank! - werde gleich mal danach schauen und dann noch eine Rückmeldung geben!

**Comment by Lacritz** [comment]
Das Problem kam natürlich während der Laufzeit, wurde mir aber während des Programm Aufrufs geworfen (was prinzipiell nicht wirklich schön ist.) --> Sprich es kam natürlich NACH dem Kompilieren. 

Das Programm sieht soweit ganz gut aus, habe es bisher rudimentär getestet und werde mir am Anfang der Woche den Code genauer Anschauen und dann auch die Rückmeldung geben!
